version: "3.8"

services:
  stirling-pdf:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: stirling-pdf
    container_name: stirling-pdf
    volumes:
      - ./training-data:/usr/share/tesseract-ocr/4.00/tessdata
      - ./extra-config:/usr/src/app/extraConfigs
      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SYSTEM_DEFAULT_LOCALE=ko-KR
      - UI_DEFAULT_LANG=ko
    ports:
      - "6080:8080"  # 프론트엔드 포트
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dev-net

networks:
  dev-net:
    name: dev-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16
          gateway: 172.50.0.1